; vim: ft=asm
; engine/joypad.inc
; Constants to interact with the joypad of the game engine.

ENGINE_PAD_DOWN      EQU     %10000000
ENGINE_PAD_UP        EQU     %01000000
ENGINE_PAD_LEFT      EQU     %00100000
ENGINE_PAD_RIGHT     EQU     %00010000
ENGINE_PAD_START     EQU     %00001000
ENGINE_PAD_SELECT    EQU     %00000100
ENGINE_PAD_B         EQU     %00000010
ENGINE_PAD_A         EQU     %00000001

