; vim: ft=asm
; hardware/lcd/sgb.inc
; Super Gameboy SGB LCD Includes

SGB_PAL01       EQU     $00
SGB_PAL23       EQU     $08
SGB_PAL03       EQU     $10
SGB_PAL12       EQU     $18
SGB_ATTR_BLK    EQU     $20
SGB_ATTR_LIN    EQU     $28
SGB_ATTR_DIV    EQU     $30
SGB_ATTR_CHR    EQU     $38
SGB_SOUND       EQU     $40
SGB_SOU_TRN     EQU     $48
SGB_PAL_SET     EQU     $50
SGB_PAL_TRN     EQU     $58
SGB_ATRC_EN     EQU     $60
SGB_TEST_EN     EQU     $68
SGB_ICON_EN     EQU     $70
SGB_DATA_SND    EQU     $78
SGB_DATA_TRN    EQU     $80
SGB_MLT_REQ     EQU     $88
SGB_JUMP        EQU     $90
SGB_CHR_TRN     EQU     $98
SGB_PCT_TRN     EQU     $A0
SGB_ATTR_TRN    EQU     $A8
SGB_ATTR_SET    EQU     $B0
SGB_MASK_EN     EQU     $B8
SGB_OBJ_TRN     EQU     $C0

