; vim: ft=asm
; engine/joypad.inc
; Constants to interact with the joypad of the game engine.

ENGINE_JOYPAD_DOWN      EQU     %10000000
ENGINE_JOYPAD_UP        EQU     %01000000
ENGINE_JOYPAD_LEFT      EQU     %00100000
ENGINE_JOYPAD_RIGHT     EQU     %00010000
ENGINE_JOYPAD_START     EQU     %00001000
ENGINE_JOYPAD_SELECT    EQU     %00000100
ENGINE_JOYPAD_B         EQU     %00000010
ENGINE_JOYPAD_A         EQU     %00000001

